[general]
working_directory = "$HOME"

[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 0.5
blur = false

[scrolling]
history = 100000

[font]
size = 12

normal = { family = "CaskaydiaCoveNerdFontMono", style = "Regular" }
bold = { family = "CaskaydiaCoveNerdFontMono", style = "Bold" }
italic = { family = "CaskaydiaCoveNerdFontMono", style = "Italic" }
bold_italic = { family = "CaskaydiaCoveNerdFontMono", style = "Bold Italic" }

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

